name: Run Scraper

on:
  schedule:
    # This cron schedule runs at 3:00 AM every day
    - cron: '30 21 * * *' 
  workflow_dispatch: # This is the line you need to add

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python 12go.py
